# Include this file from the top-level OpenResty `stream {}` context.
upstream qtnetworkchat_backend {
    server qtnetworkchat-server:8888;
}

server {
    listen 9443 ssl;
    proxy_pass qtnetworkchat_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 3600s;
    proxy_socket_keepalive on;

    ssl_certificate /etc/letsencrypt/live/qt.ziyuexc.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qt.ziyuexc.top/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:QTNetworkChatSSL:10m;
    ssl_session_timeout 10m;
}
