param(
    [string]$MarkdownPath = "docs\automation-status.md",
    [string]$Head,
    [string]$OriginMain,
    [string]$OriginCodexQt,
    [string]$CiStatus = "unknown",
    [string]$CiRunId = "",
    [string]$BuildStatus = "unknown",
    [string]$CTestStatus = "unknown",
    [int]$CTestCount = 0,
    [string[]]$ProtectedUntracked = @(".polaris/", "AGENTS.md"),
    [switch]$PlanOnly,
    [switch]$FailOnSensitive
)

$ErrorActionPreference = "Stop"

$sensitivePatterns = @(
    'password["'']?\s*[:=]\s*(?!["'']?<redacted>)',
    'PGPASSWORD["'']?\s*[:=]\s*(?!["'']?<redacted>)',
    'GPG(?:_|-|\s)?(passphrase|password|secret)["'']?\s*[:=]',
    'passphrase["'']?\s*[:=]',
    'ghp_[A-Za-z0-9_]+',
    'github_pat_[A-Za-z0-9_]+',
    'secret[-_\s]?key',
    'access[-_\s]?key',
    'session[-_\s]?token',
    'Authorization\s*[:=]',
    'Credential\s*=',
    'Signature\s*='
)

function Resolve-RepoPath([string]$PathValue) {
    if ([System.IO.Path]::IsPathRooted($PathValue)) {
        return $PathValue
    }
    Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")) $PathValue
}

function Invoke-GitText([string[]]$Arguments) {
    $output = & git @Arguments 2>$null
    if ($LASTEXITCODE -ne 0) {
        return ""
    }
    ([string]$output).Trim()
}

function Find-SensitiveHits([string[]]$Lines) {
    $hits = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $Lines.Count; ++$i) {
        foreach ($pattern in $sensitivePatterns) {
            if ($Lines[$i] -match $pattern -and $Lines[$i] -notmatch "<redacted>") {
                $hits.Add(("line {0}: {1}" -f ($i + 1), $pattern))
            }
        }
    }
    $hits
}

if ([string]::IsNullOrWhiteSpace($Head)) {
    $Head = Invoke-GitText @("rev-parse", "--short=12", "HEAD")
}
if ([string]::IsNullOrWhiteSpace($OriginMain)) {
    $OriginMain = Invoke-GitText @("rev-parse", "--short=12", "origin/main")
}
if ([string]::IsNullOrWhiteSpace($OriginCodexQt)) {
    $OriginCodexQt = Invoke-GitText @("rev-parse", "--short=12", "origin/codex/qt")
}

$normalizedProtectedUntracked = @()
foreach ($entry in $ProtectedUntracked) {
    foreach ($part in ([string]$entry -split ",")) {
        $trimmed = $part.Trim()
        if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
            $normalizedProtectedUntracked += $trimmed
        }
    }
}
$protectedText = if ($normalizedProtectedUntracked.Count -gt 0) { $normalizedProtectedUntracked -join ", " } else { "none" }
$generatedAt = (Get-Date).ToUniversalTime().ToString("o")

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# QtNetworkChat Automation Status")
$lines.Add("")
$lines.Add('Generated by `scripts/write-automation-status.ps1`. This file is intentionally sanitized; do not add passwords, tokens, GPG passphrases, endpoints with credentials, or local private paths containing secrets.')
$lines.Add("")
$lines.Add("## Current Baseline")
$lines.Add("")
$lines.Add('- Generated at: `' + $generatedAt + '`')
$lines.Add('- HEAD: `' + $Head + '`')
$lines.Add('- origin/main: `' + $OriginMain + '`')
$lines.Add('- origin/codex/qt: `' + $OriginCodexQt + '`')
$lines.Add('- GitHub Windows Build: `' + $CiStatus + '`')
$lines.Add('- GitHub run id: `' + $(if ([string]::IsNullOrWhiteSpace($CiRunId)) { "unknown" } else { $CiRunId }) + '`')
$lines.Add('- Local MinGW build: `' + $BuildStatus + '`')
$lines.Add('- Local CTest: `' + $CTestStatus + '`')
$lines.Add('- Local CTest count: `' + $CTestCount + '`')
$lines.Add('- Protected untracked entries: `' + $protectedText + '`')
$lines.Add("")
$lines.Add("## Automation Guardrails")
$lines.Add("")
$lines.Add('- Start each loop by checking repository build/test processes and `git status`.')
$lines.Add('- Preserve `.polaris/`, `AGENTS.md`, `CLAUDE.md`, and unrelated user changes.')
$lines.Add("- Use large cross-artifact slices; avoid tiny README-only or one-field patches.")
$lines.Add("- Keep PostgreSQL passwords, GPG passphrases, GitHub tokens, S3 credentials, and signed URLs out of source, docs, logs, previews, launchers, commits, and remote URLs.")
$lines.Add("- Verify with the PowerShell timeout wrappers: build 600 seconds, CTest 900 seconds.")
$lines.Add('- Use signed Conventional Commits and push `main`, then fast-forward `codex/qt`.')
$lines.Add("")
$lines.Add("## Priority Backlog")
$lines.Add("")
$lines.Add("1. Split heavy README sections into focused docs for testing coverage, PostgreSQL operations, large-file governance, and E2E hardening status.")
$lines.Add("2. Add scheduled-task status readback for database health and large-file governance tasks.")
$lines.Add("3. Continue real PostgreSQL/QPSQL boundary coverage for file chunk recovery, rollback audit, slow-query/error metrics, and connection-pool threading policy.")
$lines.Add("4. Productize E2E encryption with authenticated key agreement, real rotation, default policy, history migration, and file/chunk encryption.")
$lines.Add("5. Extend release automation with MinGW CI or release artifact path/version governance.")
$lines.Add("")
$lines.Add("## Last Local Verification")
$lines.Add("")
$lines.Add('- Build command: `cmake --build build-qt6-mingw` with 600 second timeout.')
$lines.Add('- Test command: `ctest --test-dir build-qt6-mingw --output-on-failure` with 900 second timeout.')
$lines.Add('- Real PostgreSQL smoke should use `QTNETWORKCHAT_PGPASSWORD` from the environment and `-EnsureDatabase`; generated evidence must remain redacted.')

$sensitiveHits = Find-SensitiveHits $lines
if ($sensitiveHits.Count -gt 0) {
    Write-Host "sensitive hits"
    foreach ($hit in $sensitiveHits) {
        Write-Host ("  {0}" -f $hit)
    }
    if ($FailOnSensitive) {
        exit 2
    }
}

if (-not $PlanOnly) {
    $target = Resolve-RepoPath $MarkdownPath
    $parent = Split-Path -Parent $target
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    Set-Content -LiteralPath $target -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
    Write-Host ("automation status: {0}" -f $target)
} else {
    $lines -join [Environment]::NewLine
}
