#ifndef QTNETWORKCHAT_VERSION_H
#define QTNETWORKCHAT_VERSION_H

#define QTNETWORKCHAT_VERSION_STRING "1.1.3"
#define QTNETWORKCHAT_VERSION_MAJOR 1
#define QTNETWORKCHAT_VERSION_MINOR 1
#define QTNETWORKCHAT_VERSION_PATCH 3
#define QTNETWORKCHAT_DEFAULT_SERVER_HOST ""
#define QTNETWORKCHAT_DEFAULT_SERVER_PORT 8888
#define QTNETWORKCHAT_DEFAULT_TRANSPORT "tcp"
#define QTNETWORKCHAT_DEFAULT_WEBSOCKET_PATH "/ws"
#define QTNETWORKCHAT_DEFAULT_TLS 0
#define QTNETWORKCHAT_DEFAULT_TLS_VERIFY 1

#endif // QTNETWORKCHAT_VERSION_H
