#ifndef QTNETWORKCHAT_VERSION_H
#define QTNETWORKCHAT_VERSION_H

#define QTNETWORKCHAT_VERSION_STRING "1.0.0"
#define QTNETWORKCHAT_VERSION_MAJOR 1
#define QTNETWORKCHAT_VERSION_MINOR 0
#define QTNETWORKCHAT_VERSION_PATCH 0

#endif // QTNETWORKCHAT_VERSION_H
