if(NOT DEFINED CONFIG_HEADER OR NOT EXISTS "${CONFIG_HEADER}")
    message(FATAL_ERROR "CONFIG_HEADER is required")
endif()

file(READ "${CONFIG_HEADER}" config_content)
foreach(flag IN ITEMS BACKEND_REQUESTED BACKEND_AVAILABLE ADAPTER_REQUESTED ADAPTER_LINKED)
    if(NOT DEFINED EXPECT_${flag} OR NOT "${EXPECT_${flag}}" MATCHES "^[01]$")
        message(FATAL_ERROR "EXPECT_${flag} must specify this build's 0/1 expectation")
    endif()
endforeach()

string(FIND "${config_content}" "QTNETWORKCHAT_E2E_COMPILED_BACKEND_ID \"draft-qt-hmac-stream-v1\"" backend_id_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_ID \"openssl-reviewed-adapter-v1\"" production_backend_id_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_REQUESTED_PRODUCTION_BACKEND \"${EXPECT_REQUESTED_BACKEND}\"" requested_backend_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_REQUESTED ${EXPECT_BACKEND_REQUESTED}" requested_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_AVAILABLE ${EXPECT_BACKEND_AVAILABLE}" available_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_REQUESTED ${EXPECT_ADAPTER_REQUESTED}" adapter_requested_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_LINKED ${EXPECT_ADAPTER_LINKED}" adapter_linked_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_REASON \"${EXPECT_BACKEND_REASON}\"" reason_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_REASON \"${EXPECT_ADAPTER_REASON}\"" adapter_reason_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_REQUIRED_OPERATIONS \"session-key-generation,identity-key-generation,public-key-derivation,agreement-sign,agreement-verify,session-derive,payload-encrypt,payload-decrypt\"" operations_pos)

if(backend_id_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare the draft backend id")
endif()
if(production_backend_id_pos LESS 0 OR requested_backend_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare production backend adapter identity and request evidence")
endif()
if(requested_pos LESS 0 OR available_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare production backend request/availability flags")
endif()
if(adapter_requested_pos LESS 0 OR adapter_linked_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare whether the production adapter was requested and linked")
endif()
if(reason_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare a sanitized production backend reason")
endif()
if(adapter_reason_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare a sanitized production adapter reason")
endif()
if(operations_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare the required production operation contract")
endif()

message(STATUS "E2E crypto backend config verified")
