if(NOT DEFINED SCRIPT_PATH OR NOT EXISTS "${SCRIPT_PATH}")
    message(FATAL_ERROR "SCRIPT_PATH does not exist: ${SCRIPT_PATH}")
endif()

set(TEMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/pgsql_protocol_smoke_plan")
set(FAKE_BUILD_DIR "${TEMP_DIR}/build")
set(FAKE_QT_ROOT "${TEMP_DIR}/qt")
set(FAKE_PG_BIN "${TEMP_DIR}/postgres/bin")
set(JSON_PATH "${TEMP_DIR}/pgsql-smoke-plan.json")
set(MARKDOWN_PATH "${TEMP_DIR}/pgsql-smoke-plan.md")
set(BOOTSTRAP_JSON_PATH "${TEMP_DIR}/local-postgres-bootstrap.json")
file(REMOVE_RECURSE "${TEMP_DIR}")
file(MAKE_DIRECTORY
    "${FAKE_BUILD_DIR}"
    "${FAKE_QT_ROOT}/bin"
    "${FAKE_QT_ROOT}/plugins/sqldrivers"
    "${FAKE_PG_BIN}"
)
file(WRITE "${FAKE_BUILD_DIR}/postgres_qpsql_protocol_smoke_test.exe" "fake qpsql smoke test")
file(WRITE "${FAKE_QT_ROOT}/bin/Qt6Core.dll" "fake Qt runtime")
file(WRITE "${FAKE_QT_ROOT}/plugins/sqldrivers/qsqlpsql.dll" "fake qpsql plugin")
file(WRITE "${FAKE_PG_BIN}/libpq.dll" "fake libpq")

execute_process(
    COMMAND powershell -ExecutionPolicy Bypass -File "${SCRIPT_PATH}"
        -TestExe "${FAKE_BUILD_DIR}/postgres_qpsql_protocol_smoke_test.exe"
        -QtRoot "${FAKE_QT_ROOT}"
        -PostgresBinDir "${FAKE_PG_BIN}"
        -PostgresPassword "not-used-in-plan"
        -PlanOnly
        -JsonPath "${JSON_PATH}"
        -MarkdownPath "${MARKDOWN_PATH}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error_output
)

if(NOT output STREQUAL "")
    message(STATUS "${output}")
endif()
if(NOT error_output STREQUAL "")
    message(STATUS "${error_output}")
endif()
if(NOT result EQUAL 0)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "run-pgsql-protocol-smoke.ps1 exited with code ${result}")
endif()
if(NOT EXISTS "${JSON_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan JSON was not created")
endif()
if(NOT EXISTS "${MARKDOWN_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan Markdown was not created")
endif()

file(READ "${JSON_PATH}" json_content)
file(READ "${MARKDOWN_PATH}" markdown_content)
string(JSON format GET "${json_content}" "format")
string(JSON plan_only GET "${json_content}" "planOnly")
string(JSON ok GET "${json_content}" "ok")
string(JSON ensure_database GET "${json_content}" "ensureDatabase")
string(JSON bootstrap_json_path GET "${json_content}" "bootstrapJsonPath")
string(JSON bootstrap_exit_code ERROR_VARIABLE bootstrap_exit_error GET "${json_content}" "bootstrapExitCode")
string(JSON summary_readiness GET "${json_content}" "summary" "readiness")
string(JSON summary_failed_checks GET "${json_content}" "summary" "failedCheckCount")
string(JSON summary_coverage_count GET "${json_content}" "summary" "coverageSurfaceCount")
string(JSON summary_boundary_count GET "${json_content}" "summary" "boundaryScenarioCount")
string(JSON summary_bootstrap_mode GET "${json_content}" "summary" "bootstrapMode")
string(JSON summary_operator_action GET "${json_content}" "summary" "operatorAction")
string(JSON audit_release_gate GET "${json_content}" "auditSummary" "releaseGate")
string(JSON audit_bootstrap_required GET "${json_content}" "auditSummary" "bootstrapRequired")
string(JSON audit_offline_attachment_count GET "${json_content}" "auditSummary" "offlineAttachmentScenarioCount")
string(JSON audit_resume_count GET "${json_content}" "auditSummary" "resumeScenarioCount")
string(JSON audit_failure_count GET "${json_content}" "auditSummary" "failureScenarioCount")
string(JSON audit_evidence0 GET "${json_content}" "auditSummary" "evidenceBundle" 0)
string(JSON audit_evidence2 GET "${json_content}" "auditSummary" "evidenceBundle" 2)
string(JSON audit_category0 GET "${json_content}" "auditSummary" "boundaryCategories" 0)
string(JSON audit_focus0 GET "${json_content}" "auditSummary" "auditFocus" 0)
string(JSON password GET "${json_content}" "environment" "QTNETWORKCHAT_PGPASSWORD")
string(JSON driver GET "${json_content}" "environment" "QTNETWORKCHAT_DB_DRIVER")
string(JSON coverage0 GET "${json_content}" "coverageSurfaces" 0)
string(JSON boundary0 GET "${json_content}" "boundaryScenarios" 0 "name")
string(JSON boundary0_category GET "${json_content}" "boundaryScenarios" 0 "category")
string(JSON boundary1_persistence GET "${json_content}" "boundaryScenarios" 1 "persistence")
string(FIND "${json_content}" "public-group-member-role-audit" has_group_role)
string(FIND "${json_content}" "public-group-remove-readd-marker" has_group_marker)
string(FIND "${json_content}" "offline-attachment-queue-replay" has_offline_attachment)
string(FIND "${json_content}" "offline-attachment-chunk-metadata" has_offline_attachment_metadata)
string(FIND "${json_content}" "offline-attachment-missing-file-cleanup" has_offline_attachment_missing)
string(FIND "${json_content}" "offline-attachment-size-hash-chunk-cleanup" has_offline_attachment_corruptions)
string(FIND "${json_content}" "offline-attachment-partial-ack-resume" has_offline_attachment_resume)
string(FIND "${json_content}" "offline-attachment-expired-resume-fallback" has_offline_attachment_expired_resume)
string(FIND "${json_content}" "offline-attachment-confirmed-chunks-gap-resume" has_offline_attachment_gap_resume)
string(FIND "${json_content}" "offline-attachment-all-confirmed-cleanup" has_offline_attachment_all_confirmed)
string(FIND "${json_content}" "file-chunk-metadata-persistence" has_file_chunk_boundary)
string(FIND "${json_content}" "online-file-chunk-invalid-ack-retry" has_online_file_retry)
string(FIND "${markdown_content}" "PostgreSQL QPSQL Protocol Smoke Evidence" has_markdown_title)
string(FIND "${markdown_content}" "Boundary Scenarios" has_markdown_boundaries)
string(FIND "${markdown_content}" "Ensure database: False" has_markdown_ensure_database)
string(FIND "${markdown_content}" "Bootstrap JSON: n/a" has_markdown_bootstrap_json)
string(FIND "${markdown_content}" "Readiness: ready" has_markdown_readiness)
string(FIND "${markdown_content}" "Operator action: Runtime prerequisites look ready; next run can enable real smoke against the target PostgreSQL." has_markdown_operator_action)
string(FIND "${markdown_content}" "Audit release gate: await-real-smoke" has_markdown_audit_release_gate)
string(FIND "${markdown_content}" "Audit evidence bundle: json, markdown, boundary-scenarios" has_markdown_audit_bundle)
string(FIND "${markdown_content}" "| Release gate | await-real-smoke |" has_markdown_audit_table)
string(FIND "${markdown_content}" "<redacted>" has_markdown_redacted)
string(FIND "${markdown_content}" "not-used-in-plan" has_markdown_secret)
if(NOT format STREQUAL "qtnetworkchat-pgsql-protocol-smoke-v1")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Unexpected PostgreSQL smoke format: ${format}")
endif()
if(NOT plan_only)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PlanOnly should be true")
endif()
if(NOT ok)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should pass with fake runtime files")
endif()
if(ensure_database)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PlanOnly should leave EnsureDatabase disabled by default")
endif()
if(NOT bootstrap_json_path STREQUAL "")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PlanOnly without BootstrapJsonPath should not produce a bootstrap path")
endif()
if(NOT password STREQUAL "<redacted>")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan leaked a password")
endif()
if(NOT driver STREQUAL "QPSQL")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should use QPSQL")
endif()
if(NOT coverage0 STREQUAL "register-login")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose register-login coverage")
endif()
if(NOT summary_readiness STREQUAL "ready" OR NOT summary_failed_checks EQUAL 0 OR NOT summary_coverage_count EQUAL 16 OR NOT summary_boundary_count EQUAL 12 OR NOT summary_bootstrap_mode STREQUAL "direct-connect")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose ready summary counts and direct-connect bootstrap mode")
endif()
if(NOT summary_operator_action STREQUAL "Runtime prerequisites look ready; next run can enable real smoke against the target PostgreSQL.")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose the expected operator action")
endif()
if(NOT audit_release_gate STREQUAL "await-real-smoke" OR audit_bootstrap_required OR NOT audit_offline_attachment_count EQUAL 8
    OR NOT audit_resume_count EQUAL 4 OR NOT audit_failure_count EQUAL 2 OR NOT audit_evidence0 STREQUAL "json"
    OR NOT audit_evidence2 STREQUAL "boundary-scenarios" OR NOT audit_category0 STREQUAL "file-chunk"
    OR NOT audit_focus0 STREQUAL "offline-attachment-recovery")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke audit summary should expose release gate, category counts, and audit focus")
endif()
if(has_group_role EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose public group member role audit coverage")
endif()
if(has_group_marker EQUAL -1 OR has_offline_attachment EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose group marker and offline attachment coverage")
endif()
if(NOT boundary0 STREQUAL "offline-private-queue-replay" OR NOT boundary0_category STREQUAL "offline-message")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose offline private replay as first boundary")
endif()
if(NOT boundary1_persistence STREQUAL "offline_messages.payload")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose offline attachment payload persistence")
endif()
if(has_offline_attachment_metadata EQUAL -1
    OR has_offline_attachment_missing EQUAL -1
    OR has_offline_attachment_corruptions EQUAL -1
    OR has_offline_attachment_resume EQUAL -1
    OR has_offline_attachment_expired_resume EQUAL -1
    OR has_offline_attachment_gap_resume EQUAL -1
    OR has_offline_attachment_all_confirmed EQUAL -1
    OR has_file_chunk_boundary EQUAL -1
    OR has_online_file_retry EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke plan should expose offline attachment metadata, corruption cleanup, resume fallback, confirmedChunks cleanup and online file chunk retry boundaries")
endif()
if(has_markdown_title EQUAL -1 OR has_markdown_boundaries EQUAL -1 OR has_markdown_redacted EQUAL -1 OR has_markdown_ensure_database EQUAL -1 OR has_markdown_bootstrap_json EQUAL -1 OR has_markdown_readiness EQUAL -1 OR has_markdown_operator_action EQUAL -1 OR has_markdown_audit_release_gate EQUAL -1 OR has_markdown_audit_bundle EQUAL -1 OR has_markdown_audit_table EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke Markdown should include title, readiness/operator summary, audit summary, bootstrap fields and redacted password")
endif()
if(NOT has_markdown_secret EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "PostgreSQL smoke Markdown leaked the provided password")
endif()

execute_process(
    COMMAND powershell -ExecutionPolicy Bypass -File "${SCRIPT_PATH}"
        -TestExe "${FAKE_BUILD_DIR}/postgres_qpsql_protocol_smoke_test.exe"
        -QtRoot "${FAKE_QT_ROOT}"
        -PostgresBinDir "${FAKE_PG_BIN}"
        -PostgresPassword "not-used-in-plan"
        -PlanOnly
        -EnsureDatabase
        -BootstrapJsonPath "${BOOTSTRAP_JSON_PATH}"
        -JsonPath "${JSON_PATH}.ensure.json"
        -MarkdownPath "${MARKDOWN_PATH}.ensure.md"
    RESULT_VARIABLE ensure_result
    OUTPUT_VARIABLE ensure_output
    ERROR_VARIABLE ensure_error_output
)
if(NOT ensure_result EQUAL 0)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "run-pgsql-protocol-smoke.ps1 EnsureDatabase plan exited with code ${ensure_result}")
endif()
file(READ "${JSON_PATH}.ensure.json" ensure_json_content)
file(READ "${MARKDOWN_PATH}.ensure.md" ensure_markdown_content)
string(JSON ensure_plan_only GET "${ensure_json_content}" "planOnly")
string(JSON ensure_database_enabled GET "${ensure_json_content}" "ensureDatabase")
string(JSON ensure_bootstrap_path GET "${ensure_json_content}" "bootstrapJsonPath")
string(JSON ensure_summary_bootstrap_mode GET "${ensure_json_content}" "summary" "bootstrapMode")
string(JSON ensure_summary_operator_action GET "${ensure_json_content}" "summary" "operatorAction")
string(JSON ensure_audit_release_gate GET "${ensure_json_content}" "auditSummary" "releaseGate")
string(JSON ensure_audit_bootstrap_required GET "${ensure_json_content}" "auditSummary" "bootstrapRequired")
string(FIND "${ensure_markdown_content}" "Ensure database: True" has_ensure_markdown_enabled)
string(FIND "${ensure_markdown_content}" "Bootstrap mode: ensure-database" has_ensure_markdown_bootstrap_mode)
string(FIND "${ensure_markdown_content}" "Audit release gate: await-real-smoke-with-bootstrap" has_ensure_markdown_audit_gate)
string(FIND "${ensure_markdown_content}" "not-used-in-plan" has_ensure_markdown_secret)
if(NOT ensure_plan_only OR NOT ensure_database_enabled)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "EnsureDatabase plan should expose enabled bootstrap mode")
endif()
if(NOT ensure_bootstrap_path MATCHES "local-postgres-bootstrap.json")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "EnsureDatabase plan should expose the requested bootstrap JSON path")
endif()
if(NOT ensure_summary_bootstrap_mode STREQUAL "ensure-database" OR NOT ensure_summary_operator_action STREQUAL "Bootstrap prerequisites look ready; next run can enable real smoke with EnsureDatabase.")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "EnsureDatabase plan should expose ensure-database bootstrap summary")
endif()
if(NOT ensure_audit_release_gate STREQUAL "await-real-smoke-with-bootstrap" OR NOT ensure_audit_bootstrap_required)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "EnsureDatabase plan should expose bootstrap-aware audit release gate")
endif()
if(has_ensure_markdown_enabled EQUAL -1 OR has_ensure_markdown_bootstrap_mode EQUAL -1 OR has_ensure_markdown_audit_gate EQUAL -1 OR NOT has_ensure_markdown_secret EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "EnsureDatabase plan Markdown should show bootstrap mode and audit release gate without leaking password")
endif()

file(REMOVE_RECURSE "${TEMP_DIR}")
