if(NOT DEFINED CONFIG_HEADER OR NOT EXISTS "${CONFIG_HEADER}")
    message(FATAL_ERROR "CONFIG_HEADER is required")
endif()

file(READ "${CONFIG_HEADER}" config_content)

string(FIND "${config_content}" "QTNETWORKCHAT_E2E_COMPILED_BACKEND_ID \"draft-qt-hmac-stream-v1\"" backend_id_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_ID \"openssl-reviewed-adapter-v1\"" production_backend_id_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_REQUESTED_PRODUCTION_BACKEND \"none\"" requested_backend_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_REQUESTED 0" requested_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_AVAILABLE 0" available_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_REQUESTED 0" adapter_requested_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_LINKED 0" adapter_linked_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_BACKEND_REASON \"production-backend-not-requested\"" reason_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_ADAPTER_REASON \"production-adapter-not-requested\"" adapter_reason_pos)
string(FIND "${config_content}" "QTNETWORKCHAT_E2E_PRODUCTION_REQUIRED_OPERATIONS \"session-key-generation,identity-key-generation,public-key-derivation,agreement-sign,agreement-verify,session-derive,payload-encrypt,payload-decrypt\"" operations_pos)

if(backend_id_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare the draft backend id")
endif()
if(production_backend_id_pos LESS 0 OR requested_backend_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare production backend adapter identity and request evidence")
endif()
if(requested_pos LESS 0 OR available_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare production backend request/availability flags")
endif()
if(adapter_requested_pos LESS 0 OR adapter_linked_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare whether the production adapter was requested and linked")
endif()
if(reason_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare a sanitized production backend reason")
endif()
if(adapter_reason_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare a sanitized production adapter reason")
endif()
if(operations_pos LESS 0)
    message(FATAL_ERROR "E2E crypto backend config should declare the required production operation contract")
endif()

message(STATUS "E2E crypto backend config verified")
