if(NOT DEFINED SCRIPT_PATH OR NOT EXISTS "${SCRIPT_PATH}")
    message(FATAL_ERROR "SCRIPT_PATH does not exist: ${SCRIPT_PATH}")
endif()
if(NOT DEFINED MIGRATOR_EXE OR NOT EXISTS "${MIGRATOR_EXE}")
    message(FATAL_ERROR "MIGRATOR_EXE does not exist: ${MIGRATOR_EXE}")
endif()

set(TEMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/sqlite_pg_migration_plan")
if(NOT DEFINED QT_ROOT OR NOT EXISTS "${QT_ROOT}")
    message(FATAL_ERROR "QT_ROOT is required: ${QT_ROOT}")
endif()
set(PG_BIN "${TEMP_DIR}/postgres/bin")
set(SQLITE_PATH "${TEMP_DIR}/accounts.sqlite3")
set(JSON_PATH "${TEMP_DIR}/migration-plan.json")
set(MARKDOWN_PATH "${TEMP_DIR}/migration-report.md")
set(HTML_PATH "${TEMP_DIR}/migration-report.html")
set(ROLLBACK_PREVIEW_PATH "${TEMP_DIR}/rollback-preview.json")
set(ROLLBACK_PREVIEW_MARKDOWN_PATH "${TEMP_DIR}/rollback-preview.md")
file(REMOVE_RECURSE "${TEMP_DIR}")
file(MAKE_DIRECTORY "${PG_BIN}")
file(WRITE "${PG_BIN}/libpq.dll" "fake libpq")

execute_process(
    COMMAND powershell -ExecutionPolicy Bypass -File "${SCRIPT_PATH}"
        -MigratorExe "${MIGRATOR_EXE}"
        -SQLitePath "${SQLITE_PATH}"
        -QtRoot "${QT_ROOT}"
        -PostgresBinDir "${PG_BIN}"
        -Mode plan
        -CreateSample
        -PostgresPassword "not-used-in-plan"
        -JsonPath "${JSON_PATH}"
        -MarkdownPath "${MARKDOWN_PATH}"
        -HtmlPath "${HTML_PATH}"
        -RollbackPreviewPath "${ROLLBACK_PREVIEW_PATH}"
        -RollbackPreviewMarkdownPath "${ROLLBACK_PREVIEW_MARKDOWN_PATH}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error_output
)

if(NOT output STREQUAL "")
    message(STATUS "${output}")
endif()
if(NOT error_output STREQUAL "")
    message(STATUS "${error_output}")
endif()
if(NOT result EQUAL 0)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "migrate-sqlite-to-postgres.ps1 exited with code ${result}")
endif()
if(NOT EXISTS "${JSON_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration plan JSON was not created")
endif()
if(NOT EXISTS "${MARKDOWN_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration markdown report was not created")
endif()
if(NOT EXISTS "${HTML_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration HTML report was not created")
endif()
if(NOT EXISTS "${ROLLBACK_PREVIEW_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview JSON was not created")
endif()
if(NOT EXISTS "${ROLLBACK_PREVIEW_MARKDOWN_PATH}")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview markdown was not created")
endif()

file(READ "${JSON_PATH}" json_content)
string(JSON format GET "${json_content}" "format")
string(JSON mode GET "${json_content}" "mode")
string(JSON ok GET "${json_content}" "ok")
string(JSON password GET "${json_content}" "postgresPassword")
string(JSON first_table GET "${json_content}" "tables" 0 "name")
string(JSON first_rows GET "${json_content}" "tables" 0 "rows")
string(JSON first_diff_status GET "${json_content}" "tables" 0 "diffStatus")
string(JSON first_missing_rows GET "${json_content}" "tables" 0 "missingRows")
string(JSON first_rolled_back_rows GET "${json_content}" "tables" 0 "rolledBackRows")
string(JSON summary_table_count GET "${json_content}" "diffSummary" "tableCount")
string(JSON summary_source_rows GET "${json_content}" "diffSummary" "totalSourceRows")
string(JSON summary_missing_rows GET "${json_content}" "diffSummary" "totalMissingRows")
string(JSON summary_severity GET "${json_content}" "diffSummary" "severity")
string(JSON summary_action GET "${json_content}" "diffSummary" "recommendedAction")
string(JSON summary_drift_tables GET "${json_content}" "diffSummary" "driftTableCount")
file(READ "${MARKDOWN_PATH}" markdown_content)
file(READ "${HTML_PATH}" html_content)
file(READ "${ROLLBACK_PREVIEW_PATH}" preview_content)
string(JSON preview_format GET "${preview_content}" "format")
string(JSON preview_dry_run GET "${preview_content}" "dryRun")
string(JSON preview_password GET "${preview_content}" "postgresPassword")
string(JSON preview_risk_level GET "${preview_content}" "riskLevel")
string(JSON preview_total_would_delete_rows GET "${preview_content}" "summary" "totalWouldDeleteRows")
string(JSON preview_tables_with_deletes GET "${preview_content}" "summary" "tablesWithDeletes")
string(JSON preview_operation_table GET "${preview_content}" "operations" 0 "table")
string(JSON preview_operation_shape GET "${preview_content}" "operations" 0 "whereShape")
string(JSON preview_operation_review GET "${preview_content}" "operations" 0 "requiresReview")
string(JSON preview_table GET "${preview_content}" "tables" 0 "name")
string(JSON preview_table_delete_rows GET "${preview_content}" "tables" 0 "wouldDeleteRows")
file(READ "${ROLLBACK_PREVIEW_MARKDOWN_PATH}" preview_markdown_content)
string(FIND "${markdown_content}" "SQLite to PostgreSQL Migration Report" markdown_title)
string(FIND "${markdown_content}" "<redacted>" markdown_redacted)
string(FIND "${markdown_content}" "Diff severity: ok" markdown_diff_severity)
string(FIND "${markdown_content}" "Recommended action: No migration drift detected." markdown_diff_action)
string(FIND "${html_content}" "<table>" html_table)
string(FIND "${html_content}" "<h2>Diff Summary</h2>" html_diff_summary)
string(FIND "${html_content}" "Recommended action" html_diff_action)
string(FIND "${html_content}" "not-used-in-plan" html_secret)
string(FIND "${preview_markdown_content}" "SQLite to PostgreSQL Rollback Dry-run Preview" preview_markdown_title)
string(FIND "${preview_markdown_content}" "<redacted>" preview_markdown_redacted)
string(FIND "${preview_markdown_content}" "not-used-in-plan" preview_markdown_secret)
if(NOT format STREQUAL "qtnetworkchat-sqlite-pg-migration-v1")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Unexpected migration format: ${format}")
endif()
if(NOT mode STREQUAL "plan")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration mode should be plan")
endif()
if(NOT ok)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration plan should be ok")
endif()
if(NOT password STREQUAL "<redacted>")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration plan leaked PostgreSQL password")
endif()
if(NOT first_table STREQUAL "accounts")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "First migration table should be accounts")
endif()
if(NOT first_rows EQUAL 1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Sample accounts row count should be 1")
endif()
if((NOT "${first_diff_status}" STREQUAL "clean") OR (NOT first_missing_rows EQUAL 0) OR (NOT first_rolled_back_rows EQUAL 0))
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration plan should include clean diff/rollback counters")
endif()
if((NOT "${summary_table_count}" EQUAL 10) OR (NOT "${summary_source_rows}" EQUAL 5) OR (NOT "${summary_missing_rows}" EQUAL 0) OR (NOT "${summary_drift_tables}" EQUAL 0))
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration diff summary has unexpected counts")
endif()
if((NOT "${summary_severity}" STREQUAL "ok") OR (NOT "${summary_action}" STREQUAL "No migration drift detected."))
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration diff summary should expose ok severity and action")
endif()
if(NOT preview_format STREQUAL "qtnetworkchat-sqlite-pg-rollback-preview-v1")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview format mismatch: ${preview_format}")
endif()
if(NOT preview_dry_run)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview should be dry-run")
endif()
if(NOT preview_password STREQUAL "<redacted>")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview leaked PostgreSQL password")
endif()
if(NOT preview_risk_level STREQUAL "review")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview should require review for non-empty plan")
endif()
if(NOT preview_total_would_delete_rows EQUAL 5 OR NOT preview_tables_with_deletes EQUAL 5)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview summary has unexpected delete totals")
endif()
if(NOT preview_operation_table STREQUAL "accounts" OR NOT preview_operation_shape STREQUAL "account = ?" OR NOT preview_operation_review)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview operation should describe accounts delete shape and review gate")
endif()
if(NOT preview_table STREQUAL "accounts")
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview should include accounts table")
endif()
if(NOT preview_table_delete_rows EQUAL 1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview should count sample accounts delete rows")
endif()
if(markdown_title EQUAL -1 OR markdown_redacted EQUAL -1 OR markdown_diff_severity EQUAL -1 OR markdown_diff_action EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration markdown report missing title, redaction, or diff summary")
endif()
if(html_table EQUAL -1 OR html_diff_summary EQUAL -1 OR html_diff_action EQUAL -1 OR NOT html_secret EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Migration HTML report missing table/diff summary or leaked password")
endif()
if(preview_markdown_title EQUAL -1 OR preview_markdown_redacted EQUAL -1 OR NOT preview_markdown_secret EQUAL -1)
    file(REMOVE_RECURSE "${TEMP_DIR}")
    message(FATAL_ERROR "Rollback preview markdown missing title/redaction or leaked password")
endif()

file(REMOVE_RECURSE "${TEMP_DIR}")
